/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.GCMixto;

/**
 *
 * @author Administrator
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private GCMixto gcMixto;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jRmixto.setSelected(true);
        jRMulti.setSelected(false);
        establecerColumnas();
        //model.addRow(new Object[]{"v1", "v2"});
    }
    private void establecerColumnas(){
        model = new DefaultTableModel(); 
        if(jRmixto.isSelected()){
            model.addColumn("n"); 
            model.addColumn("Xn"); 
            model.addColumn("aXn"); 
            model.addColumn("aXn+c"); 
            model.addColumn("Xn+1"); 
            model.addColumn("Un+1");
        }else{
            model.addColumn("n"); 
            model.addColumn("Xn"); 
            model.addColumn("aXn"); 
            model.addColumn("Xn+1"); 
            model.addColumn("Un+1");
        }
         
        jTableResultado.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jTextFieldM = new javax.swing.JTextField();
        jTextFieldA = new javax.swing.JTextField();
        jTextFieldXo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRmixto = new javax.swing.JRadioButton();
        jRMulti = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();
        jbuttonEncontrar = new javax.swing.JButton();
        jButtonGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));

        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Xn", "aXn", "aXn+c", "Xn+1", "Un+1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResultado);
        if (jTableResultado.getColumnModel().getColumnCount() > 0) {
            jTableResultado.getColumnModel().getColumn(0).setResizable(false);
            jTableResultado.getColumnModel().getColumn(1).setResizable(false);
            jTableResultado.getColumnModel().getColumn(2).setResizable(false);
            jTableResultado.getColumnModel().getColumn(3).setResizable(false);
            jTableResultado.getColumnModel().getColumn(4).setResizable(false);
            jTableResultado.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setText("generador de numeros pseudoaleatorios");

        jLabel2.setText("a");

        jLabel3.setText("c");

        jLabel4.setText("m");

        jRmixto.setText("generador C. Mixto");
        jRmixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmixtoActionPerformed(evt);
            }
        });

        jRMulti.setText("generador C. Multiplicativo");
        jRMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMultiActionPerformed(evt);
            }
        });

        jLabel5.setText("xo");

        jbuttonEncontrar.setText("encontrar un generador");
        jbuttonEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonEncontrarActionPerformed(evt);
            }
        });

        jButtonGenerar.setText("generar tabla");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel5)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRmixto))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRMulti)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jbuttonEncontrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonGenerar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldXo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabelMensaje)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRmixto)
                    .addComponent(jRMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldXo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMensaje)
                    .addComponent(jbuttonEncontrar)
                    .addComponent(jButtonGenerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMultiActionPerformed
        // TODO add your handling code here:
        jRMulti.setSelected(true);
        jRmixto.setSelected(false);
        limpiarTabla();
        establecerColumnas();
        jbuttonEncontrar.setVisible(false);
        jTextFieldC.setText("0");
        jTextFieldC.setEditable(false);
    }//GEN-LAST:event_jRMultiActionPerformed

    private void jbuttonEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonEncontrarActionPerformed
        // TODO add your handling code here:
        //limpiarTabla();
         // a jframe here isn't strictly necessary, but it makes the example a little more real
        JFrame frame = new JFrame("buscar generador");
        String ent = JOptionPane.showInputDialog(frame, "ingrese el valor para m");
        try{
            int m=Integer.parseInt(ent);
            int valorMin=2;
            if(m>valorMin){
                gcMixto=new GCMixto(m);
                if(gcMixto.esGeneradorCompleto()){
                    jTextFieldA.setText(gcMixto.getA()+"");
                    jTextFieldC.setText(gcMixto.getC()+"");
                    jTextFieldM.setText(gcMixto.getM()+"");
                    jTextFieldXo.setText(gcMixto.getXo()+"");
                    jLabelMensaje.setText("");
                }else{
                    JOptionPane.showMessageDialog(frame, "no existe generador completo para "+m);
                }
            }else{
                JOptionPane.showMessageDialog(null, "el valor de m debe ser mayor a "+valorMin);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(frame, "el valor de m debe ser un numero");
        }
        
    }//GEN-LAST:event_jbuttonEncontrarActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        try{
            int a=Integer.parseInt(jTextFieldA.getText());
            int c=Integer.parseInt(jTextFieldC.getText());
            int m=Integer.parseInt(jTextFieldM.getText());
            int xo=Integer.parseInt(jTextFieldXo.getText());
            if(verificarDatos(a,c,m,xo)){
                gcMixto=new GCMixto(a, c, m, xo);
                gcMixto.generarNumeros2();
                if(jRmixto.isSelected()){
                    if(gcMixto.esPeriodoCompleto()){
                        jLabelMensaje.setText("generador de periodo completo "+m);
                        jLabelMensaje.setForeground(Color.blue);
                    }else{    
                        jLabelMensaje.setText("NO es un generador de periodo completo ");
                        jLabelMensaje.setForeground(Color.red);
                    }
                }else{
                    
                }
                agregarFilas(gcMixto.getResultadoGenerado());
                
            }else{
                JOptionPane.showMessageDialog(null, "los numeros no son validos");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "introduzca numeros plox");
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed
    private boolean verificarDatos(int a,int c,int m,int xo){
        return m>a&&m>c&&m>xo;
    }
    private void agregarFilas(ArrayList<GCMixto> listaRes){
        Object[] aux;
        int cont=0;
        if(jRmixto.isSelected()){
            for(GCMixto gc:listaRes){
                aux=new Object[6];
                aux[0]=cont;
                aux[1]=gc.getXo();
                aux[2]=gc.getA()*gc.getXo();
                aux[3]=gc.getA()*gc.getXo()+gc.getC();
                aux[4]=gc.getXn();
                aux[5]=gc.getUn();
                model.addRow(aux);
                cont++;
            }
        }else{
            for(GCMixto gc:listaRes){
                aux=new Object[6];
                aux[0]=cont;
                aux[1]=gc.getXo();
                aux[2]=gc.getA()*gc.getXo();
                aux[3]=gc.getXn();
                aux[4]=gc.getUn();
                model.addRow(aux);
                cont++;
            }
        }
        
    }
    public void limpiarTabla(){
        //DefaultTableModel tb = (DefaultTableModel) Jtable.getModel();
        int a=jTableResultado.getRowCount();
        //System.out.println("tamaño"+a);
        for(int i=0;i<a;i++){  
            model.removeRow(0);
        }
        jLabelMensaje.setText("");
    }
    private void jRmixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmixtoActionPerformed
        // TODO add your handling code here:
        jRmixto.setSelected(true);
        jRMulti.setSelected(false);
        limpiarTabla();
        establecerColumnas();
        
        jbuttonEncontrar.setVisible(true);
        jTextFieldC.setText("");
        jTextFieldC.setEditable(true);
    }//GEN-LAST:event_jRmixtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JRadioButton jRMulti;
    private javax.swing.JRadioButton jRmixto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldXo;
    private javax.swing.JButton jbuttonEncontrar;
    // End of variables declaration//GEN-END:variables
}
